### ISSUE TITLE
Needed help, with selecting the version of os_patching module..

### ISSUE THREAD

**Issue by sandeep0012** [albatrossflavour/puppet_os_patching#194]
Hi Team,

 I just got introduced to Puppet in the current company. We would like to use this module for the immediate Infra task activity. 

We have configured puppet agent and Master using below repo version.. 
        yum -y install http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm
 when i run below command on the node , it shows 3.8.7 
       >> puppet --version  >> 3.8.7 
However on the documentation site,  https://forge.puppet.com/modules/albatrossflavour/os_patching/0.1.0 , it shows to be support This version is compatible with:
Puppet Enterprise 2018.1.x, 2017.3.x, 2017.2.x, 2017.1.x, 2016.5.x, 2016.4.x
**Puppet >= 4.7.0 < 6.0.0**

Which version of OS Patching module should I select for Puppet version 3.8.7 , Amazaon Linux 2 OS.

Your help is much crucial for us, looking forward to hear back from you..

Regards,
Suraj

**Comment by TJM** [comment]
Puppet 3.8.7 has been end of life for a *very* long time (years), Even Puppet 5.5.x is end of life, as far as I know. 

I don't know about Amazon Linux, but if you are using "EL6" puppet, I would venture a guess that there are no longer updates being released for it either.

Your mileage may vary, anything you try will not be supportable. Sorry ;)

**Comment by albatrossflavour** [comment]
Yeah, I agree with @TJM.  You should steer towards a more recent release of Puppet.

Since you're running Amazon Linux 2, you should install the EL7 stream, which is what that is based off (yay amazon for their naming standards!)

There is a pretty good guide [here](https://techviewleo.com/install-puppet-server-on-amazon-linux/) that covers puppet open source.

If you run into trouble, you can get help on the [Puppet community slack](http://slack.puppet.com).  @TJM and I can both be found on there.
